GIT_REPO: https://github.com/sakshit1441/mongodb-ansible.git
GIT_BRANCH: Sakshi_Totawar_Ansible

ENVIRONMENT: dev

KEEP_APPROVAL_STAGE: true

CODE_BASE_PATH: mongodb-ansible
ANSIBLE_PLAYBOOK: site.yml
INVENTORY_FILE: inventory/dev.ini

SLACK_CHANNEL_NAME: "#mongodb-deployments"
ACTION_MESSAGE: "MongoDB deployment completed"
